import { useState } from 'react'
import SearchBar from '../components/SearchBar'
import { Sparkles } from 'lucide-react'

const Dashboard = () => {
  const popularStocks = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA']

  return (
    <div className="space-y-8">
      {/* Hero Section */}
      <div className="card bg-gradient-to-r from-primary-600 to-primary-700 text-white">
        <div className="flex items-center gap-3 mb-4">
          <Sparkles className="h-8 w-8" />
          <h1 className="text-3xl font-bold">
            AI-Powered Market Insights
          </h1>
        </div>
        <p className="text-lg text-primary-50 mb-6">
          Get real-time stock data, AI-generated analysis, and personalized recommendations
        </p>
        <SearchBar />
      </div>

      {/* Popular Stocks */}
      <div>
        <h2 className="text-2xl font-bold mb-4">Popular Stocks</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
          {popularStocks.map((symbol) => (
            <a
              key={symbol}
              href={`/stock/${symbol}`}
              className="card hover:shadow-lg transition-shadow text-center"
            >
              <div className="font-bold text-xl text-gray-900">{symbol}</div>
            </a>
          ))}
        </div>
      </div>

      {/* Features */}
      <div className="grid md:grid-cols-3 gap-6">
        <div className="card">
          <div className="text-4xl mb-3">📊</div>
          <h3 className="text-lg font-bold mb-2">Live Stock Data</h3>
          <p className="text-gray-600">
            Real-time prices, charts, and financial metrics powered by Finnhub API
          </p>
        </div>

        <div className="card">
          <div className="text-4xl mb-3">🤖</div>
          <h3 className="text-lg font-bold mb-2">AI Analysis</h3>
          <p className="text-gray-600">
            Natural language insights and recommendations generated by advanced AI
          </p>
        </div>

        <div className="card">
          <div className="text-4xl mb-3">⭐</div>
          <h3 className="text-lg font-bold mb-2">Personal Watchlist</h3>
          <p className="text-gray-600">
            Track your favorite stocks and get instant updates on price changes
          </p>
        </div>
      </div>

      {/* Getting Started */}
      <div className="card">
        <h2 className="text-2xl font-bold mb-4">Getting Started</h2>
        <ol className="space-y-3 text-gray-700">
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-primary-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
              1
            </span>
            <span>Search for any stock using the search bar above</span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-primary-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
              2
            </span>
            <span>View real-time data, news, and AI-generated insights</span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-primary-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
              3
            </span>
            <span>Add stocks to your watchlist for easy tracking</span>
          </li>
        </ol>
      </div>
    </div>
  )
}

export default Dashboard
